Update thug.yaml

diff --git a/.github/workflows/thug.yaml b/.github/workflows/thug.yaml
--- a/.github/workflows/thug.yaml
+++ b/.github/workflows/thug.yaml
@@ -55,6 +55,20 @@ jobs:
           git config --global user.name "GitHub Actions"
           git config --global user.email "github-actions@users.noreply.github.com"
           git config --global init.defaultBranch main  # Définit la branche initiale à 'main'
+      
+      - name: Check release assets via API (Debug)
+        env:
+          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }} # Utilisez le PAT ici si nécessaire
+        run: |
+          echo "Fetching release assets from GitHub API..."
+          RESPONSE=$(curl -s -w "%{http_code}" -H "Authorization: token $GITHUB_TOKEN" \
+            "https://api.github.com/repos/umr-marbec/test_miroir/releases/${RELEASE_ID}/assets")
+          echo "Response Code: $RESPONSE"
+          if [ "${RESPONSE}" -ge 400 ]; then
+            echo "Error fetching release assets. HTTP status code: $RESPONSE"
+            exit 1
+          fi
+          echo "$RESPONSE" | jq
 
       - name: Fetch the latest release
         id: fetch_release
